import { StyleSheet } from "react-native";
import { ThemeColors } from "../theme";

export default (c: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 76,
      paddingBottom: 20,
      backgroundColor: c.background,
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.5,
      color: c.accent,
      marginBottom: 7,
    },
    title: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800",
      color: c.textPrimary,
    },
    emptyMessage: {
      maxWidth: 280,
      marginTop: 12,
      marginBottom: 24,
      fontSize: 15,
      lineHeight: 22,
      textAlign: "center",
      color: c.textSecondary,
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    gaugeCard: {
      marginTop: 10,
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderRadius: 16,
      backgroundColor: c.gaugeCard,
      alignItems: "flex-start",
      borderWidth: 1,
      borderColor: c.accentSoft,
      minWidth: 190,
    },
    gaugeLabel: {
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.2,
      color: c.textSecondary,
      marginBottom: 4,
    },
    gaugeValueRow: {
      flexDirection: "row",
      alignItems: "baseline",
    },
    gaugeValue: {
      fontSize: 34,
      lineHeight: 38,
      fontWeight: "800",
      color: c.textPrimary,
    },
    gaugeUnit: {
      marginLeft: 5,
      fontSize: 16,
      fontWeight: "700",
      color: c.accent,
    },
    gaugeSubValue: {
      marginTop: 2,
      fontSize: 13,
      fontWeight: "600",
      color: c.textSecondary,
    },
    distanceLabel: {
      fontSize: 12,
      color: c.textMuted,
      marginTop: 8,
    },
    box: {
      marginTop: 20,
      padding: 15,
      borderWidth: 1,
      borderRadius: 12,
    },
    connectedContainer: {
      flex: 1,
      marginTop: 8,
      justifyContent: "space-between",
    },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingBottom: 18,
    },
    nameRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 0,
      borderWidth: 1,
      borderColor: c.surfaceBorder,
      paddingHorizontal: 12,
      paddingVertical: 13,
      borderRadius: 14,
      backgroundColor: c.surfaceElevated,
    },
    strengthWrap: {
      minWidth: 120,
    },

    separator: {
      width: 1,
      height: 40,
      backgroundColor: c.surfaceBorder,
      marginHorizontal: 12,
      alignSelf: "center",
    },

    batteryWrap: {
      marginLeft: 0,
    },
    carWrap: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 12,
    },
    bottomRow: {
      alignItems: "center",
      position: "relative",
      paddingTop: 12,
      paddingBottom: 28,
      zIndex: 10,
    },
    name: {
      fontSize: 22,
      fontWeight: "800",
      color: c.textPrimary,
    },
    subtitle: {
      fontSize: 24,
      fontWeight: "800",
      marginTop: 5,
      color: c.textPrimary,
    },
    button: {
      marginTop: 16,
      alignSelf: "center",
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: c.buttonBg,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: "600",
      color: c.buttonText,
      marginTop: -56,
      backgroundColor: "gray",
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
    },
  });
